#!/usr/bin/env bash

# Location of script
HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd ${HERE}/../..

docker run -v ${PWD}/tf:/tf -w /tf -it --rm hashicorp/terraform:light $@
